import { useState, type FormEvent } from "react";
import type { FirebaseError } from "firebase/app";
import { useNavigate } from "react-router-dom";
import { useAuth } from "../auth";
import { registerStudentWithAccessKey } from "../firestoreApi";

type AuthMode = "signin" | "register";

export function LoginPage(): JSX.Element {
  const { signIn } = useAuth();
  const navigate = useNavigate();
  const [mode, setMode] = useState<AuthMode>("signin");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [displayName, setDisplayName] = useState("");
  const [accessKey, setAccessKey] = useState("");
  const [status, setStatus] = useState("");
  const [busy, setBusy] = useState(false);

  async function handleSubmit(event: FormEvent<HTMLFormElement>): Promise<void> {
    event.preventDefault();
    setBusy(true);
    setStatus("");

    try {
      await signIn(email.trim(), password);
      navigate("/module/pilot-vertragsrecht", { replace: true });
    } catch (error) {
      setStatus(formatLoginError(error));
    } finally {
      setBusy(false);
    }
  }

  async function handleRegister(event: FormEvent<HTMLFormElement>): Promise<void> {
    event.preventDefault();
    setBusy(true);
    setStatus("");

    try {
      await registerStudentWithAccessKey({
        email: email.trim(),
        password,
        accessKey: accessKey.trim(),
        displayName: displayName.trim() || undefined
      });

      await signIn(email.trim(), password);
      navigate("/module/pilot-vertragsrecht", { replace: true });
    } catch (error) {
      setStatus(formatRegistrationError(error));
    } finally {
      setBusy(false);
    }
  }

  function switchMode(nextMode: AuthMode): void {
    setMode(nextMode);
    setStatus("");
  }

  return (
    <main className="auth-page">
      <section className="auth-card">
        <h1>{mode === "signin" ? "Course Login" : "Student Registration"}</h1>
        <p>
          {mode === "signin"
            ? "Sign in with your Firebase account to access the module player."
            : "Create your student account with the class access key from your teacher."}
        </p>

        <div className="auth-mode-switch" role="group" aria-label="Authentication mode">
          <button
            type="button"
            className={mode === "signin" ? "secondary-btn active" : "secondary-btn"}
            onClick={() => switchMode("signin")}
            disabled={busy}
          >
            Sign in
          </button>
          <button
            type="button"
            className={mode === "register" ? "secondary-btn active" : "secondary-btn"}
            onClick={() => switchMode("register")}
            disabled={busy}
          >
            Register
          </button>
        </div>

        <form onSubmit={mode === "signin" ? handleSubmit : handleRegister}>
          <label htmlFor="email">Email</label>
          <input
            id="email"
            type="email"
            value={email}
            onChange={(event) => setEmail(event.target.value)}
            required
          />

          <label htmlFor="password">Password</label>
          <input
            id="password"
            type="password"
            value={password}
            onChange={(event) => setPassword(event.target.value)}
            minLength={8}
            required
          />

          {mode === "register" ? (
            <>
              <label htmlFor="display-name">Display name (optional)</label>
              <input
                id="display-name"
                type="text"
                value={displayName}
                onChange={(event) => setDisplayName(event.target.value)}
              />

              <label htmlFor="access-key">Student access key</label>
              <input
                id="access-key"
                type="text"
                value={accessKey}
                onChange={(event) => setAccessKey(event.target.value)}
                minLength={12}
                required
              />

              <p className="auth-help-text">
                Password must be at least 8 characters. Access key is generated by the admin panel.
              </p>
            </>
          ) : null}

          <button type="submit" disabled={busy}>
            {busy
              ? mode === "signin"
                ? "Signing in..."
                : "Registering..."
              : mode === "signin"
                ? "Sign in"
                : "Register and sign in"}
          </button>
        </form>

        {status ? <p className="form-status">{status}</p> : null}
      </section>
    </main>
  );
}

function formatLoginError(error: unknown): string {
  const firebaseError = error as FirebaseError | undefined;
  const code = firebaseError?.code ?? "";

  if (
    code === "auth/invalid-credential" ||
    code === "auth/user-not-found" ||
    code === "auth/wrong-password" ||
    code === "auth/invalid-email"
  ) {
    return "Login failed. Check email and password.";
  }

  return "Login failed. Please try again.";
}

function formatRegistrationError(error: unknown): string {
  const firebaseError = error as FirebaseError | undefined;
  const code = firebaseError?.code ?? "";
  const message = typeof firebaseError?.message === "string" ? firebaseError.message : "";
  const details =
    typeof (firebaseError as { details?: unknown } | undefined)?.details === "string"
      ? String((firebaseError as { details?: unknown }).details)
      : "";

  if (code === "functions/already-exists") {
    return "This email is already registered. Please sign in instead.";
  }

  if (code === "functions/invalid-argument") {
    const joined = `${details} ${message}`.toLowerCase();
    if (joined.includes("password")) {
      return "Password must be at least 8 characters.";
    }
    return details || message || "Invalid registration data. Check email, password, and access key.";
  }

  if (code === "functions/permission-denied" || code === "functions/resource-exhausted") {
    return "Access key is invalid, expired, or fully used.";
  }

  if (code === "functions/internal") {
    return "Registration failed due to a server error. Try again in a moment.";
  }

  return "Registration failed. Check email, password, and access key.";
}
